// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:nawy_ai_app/app/features/favorites/data/sources/local/models/area_hive.dart';
import 'package:nawy_ai_app/app/features/favorites/data/sources/local/models/compound_hive.dart';
import 'package:nawy_ai_app/app/features/favorites/data/sources/local/models/developer_hive.dart';
import 'package:nawy_ai_app/app/features/favorites/data/sources/local/models/property_hive.dart';
import 'package:nawy_ai_app/app/features/favorites/data/sources/local/models/property_type_hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AreaHiveAdapter());
    registerAdapter(CompoundHiveAdapter());
    registerAdapter(DeveloperHiveAdapter());
    registerAdapter(PropertyHiveAdapter());
    registerAdapter(PropertyTypeHiveAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AreaHiveAdapter());
    registerAdapter(CompoundHiveAdapter());
    registerAdapter(DeveloperHiveAdapter());
    registerAdapter(PropertyHiveAdapter());
    registerAdapter(PropertyTypeHiveAdapter());
  }
}
